// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  countdown: dynamic(() => import("./Countdown")),
  hero: dynamic(() => import("./Hero")),
};
